### ISSUE TITLE
All values are converted to string leading to problems with aggregation in Grafana

### ISSUE THREAD

**Issue by jastBytes** [rifatx/Serilog.Sinks.InfluxDB#1]
The sink converts the values of all properties of the log event to string before sending the point to InfluxDB. 

This leads to the error message "unsupported iterator type: *query.stringInterruptIterator" when you try to do aggregations on properties within Grafana for example.

In my case I was trying to show a graph with the average execution time of certain api calls in milliseconds.

**Comment by rifatx** [comment]
thanks for the fix.
